name: cocktail_app
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_launcher_icons: 0.9.1

  url_launcher: ^6.0.9

  # state management
  provider: ^4.3.3

  http: ^0.12.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
   image_path: "assets/images/logo-shizzi.png"
   android: true
   ios: true

flutter:
  uses-material-design: true



  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/sad.jpg
    - assets/images/1.jpg
    - assets/drink_codes.json
    - assets/ingredient_codes.json
