version: "3.7"

services:
  postgres-db:
    image: postgres:12.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      #POSTGRES_DB: mydb
      #POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes: 
  pgdata: