# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Box Settings
  config.vm.box = "centos/7"
  config.vm.hostname = "ioartigiano-be"
  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end


  config.vm.network "private_network", ip: "192.168.12.34"
  config.vm.network "forwarded_port", guest: 5000, host: 5000 #For Golang Service

  # Folder Settings
  config.vm.synced_folder ".", "/opt/ioartigiano-be",
  type: "rsync"
  
  config.vm.provision "shell", path: "provisioning/setup.sh"
  config.vm.provision "shell", path: "provisioning/db-setup.sh"
  config.vm.provision "shell", path: "provisioning/adminer-setup.sh"
  config.vm.provision "shell", path: "provisioning/nginx.sh"

end
